---
title: "Tutorial Django 001"
author: "Lic. Diego Saavedra Mg. Sc."
date: today
execute: 
  enabled: true
format: 
  pdf:
    lang: es
    toc: true #
    #toc-title: Tutorial de Django 001
    toc-depth: 3
    number-sections: true
    colorlinks: true
    documentclass: report #tipo de documento
    papersize: A4
    #lof: true #lista de figuras
    #lot: true #ista de tablas
    highlight-style: radical #Resaltado de código
    fontfamily: libertinus #Fuente de Texto
    
    cite-method: biblatex
    bibliography: references.bib
    cls: apa.csl
    biblio-title: Bibliografía
---

# Crear el espacio de trabajo. {.unnumbered .unlisted}

Este tutoríal es publicado siguiendo los lineamientos de @school2022

A continuación se describe una serie de comandos que le permitirá crear su espacio de trabajo tomando en cuenta algunos aspectos:

1.  Entorno Virtual.
2.  Activación del Entorno Virtual.
3.  Creación del Archivo .gitignore.
4.  Subir el repositorio a Github.

## Comando para crear el Entorno Virtual.

```{bash}
python -m venv .env
```

## Comando para activar el entorno virtual.

```{bash}
source .env/bin/activate
```

## Comando para desactivar el entorno virtual.

```{bash}
deactivate
```

## Comando para crear un Proyecto en Django.

```{bash}
django-admin createproject nombre_del_proyecto .
```

## Comando para crear una app en Django.

```{bash}
django-admin createapp nombre_de_la_app
```

## Comando para correr el servidor.

```{bash}
python manage.py runserver
```

## Comando para detener el servidor

No existe un comando para detener el servidor local, pero puedes utilizar la combinación de teclas:

```{bash}
Ctrl + c
```

[Repositorio en Github](https://github.com/5t4t1ck/project)
